### ISSUE TITLE
哪里开源了？

### ISSUE THREAD

**Issue by xinkeji** [tgnav/tgnav.github.io#3]

**Comment by AndaBrown** [comment]
这个储存库存放的就是网站的源代码，网站就是用这个储存库部署出来的。

**Comment by xinkeji** [comment]
这不是hugo嘛

**Comment by AndaBrown** [comment]
> 这不是hugo嘛

是啊

**Comment by xinkeji** [comment]
可以看下hogo源码嘛，主要想看看go页面😂😂



---原始邮件---
发件人: "Anda ***@***.***&gt;
发送时间: 2024年3月12日(周二) 晚上9:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tgnav/tgnav.github.io] 哪里开源了？ (Issue #3)




  
这不是hugo嘛
  
是啊

**Comment by AndaBrown** [comment]
> 可以看下hogo源码嘛，主要想看看go页面😂😂
> 
> 
> 
> ---原始邮件---
> 发件人: "Anda ***@***.***&gt;
> 发送时间: 2024年3月12日(周二) 晚上9:55
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [tgnav/tgnav.github.io] 哪里开源了？ (Issue #3)
> 
> 
> 
> 
>   
> 这不是hugo嘛
>   
> 是啊
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

go页面也是开源的哇，仓库里面有
